---
- name: Create a vulnerable struts application
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Create project for struts app
      k8s:
        state: present
        src: files/devops-project.yml

    - name: Create struts service account
      shell: oc get sa struts-sa -n devops || oc create sa struts-sa -n devops
    
    - name: Add cluster-admin to struts service account
      shell: oc adm policy add-role-to-user cluster-admin -z struts-sa -n devops
    
    - name: Deploy struts app
      k8s:
        state: present
        src: files/struts-deployment.yml

    - name: Create struts service
      shell: oc get svc struts-app -n devops || oc expose deployment/struts-app --port 8080 -n devops

    - name: Create struts route
      shell: oc get route struts-app -n devops || oc expose svc struts-app -n devops
