---
- name: Create a vulnerable struts application
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Create project for struts app
      k8s:
        state: present
        src: files/devops-project.yml

    - name: Create struts service account
      shell: oc get sa struts-sa -n smartgates || oc create sa struts-sa -n smartgates

    - name: Add cluster-admin to struts service account
      shell: oc adm policy add-role-to-user cluster-admin -z struts-sa -n smartgates

    - name: Deploy struts app
      k8s:
        state: present
        src: files/struts-deployment.yml

    - name: Create struts service
      shell: oc get svc cbr-smartgate -n smartgates || oc expose deployment/cbr-smartgate --port 8080 -n smartgates

    - name: Create struts route
      shell: oc get route cbr-smartgate -n smartgates || oc expose svc cbr-smartgate -n smartgates

    - name: Store struts route
      shell: oc get route cbr-smartgate -n smartgates -o json | jq -r .spec.host
      register: struts_route
